apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: fathom-cert
  namespace: fathom
spec:
  secretName: fathom-tls
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  dnsNames:
  - track.weeklytechie.com
  - track.stirichina.ro
  acme:
    config:
    - dns01:
        provider: cloudfront-dns
      domains:
      - track.weeklytechie.com
      - track.stirichina.ro